from __future__ import annotations

from collections import defaultdict

from sqlalchemy.orm import Session

from ..models import ADR, API, Artifact, ArchitecturePackage, DataEntity, Event, Requirement, Service


def _traceability(reqs: list[Requirement], adrs: list[ADR]) -> dict:
    return {
        "requirements": [r.key for r in reqs],
        "adrs": [adr.title for adr in adrs],
        "citations": ["ArchSmith Architecture Standards v1", "PRD FR1-FR6"],
    }


def _domain_doc(package: ArchitecturePackage) -> str:
    lines = [f"# {package.name} — Domain Model", "", package.description, "", "## Domains"]
    for domain in package.domains:
        lines.append(f"\n### {domain.name}")
        lines.append(f"{domain.description}")
    lines.append("\n## Bounded Contexts")
    for bc in package.bounded_contexts:
        lines.append(f"- **{bc.name}** → Domain: `{bc.domain_name}`")
    lines.append("\n## Services")
    for svc in package.services:
        lines.append(f"- **{svc.name}** (`{svc.service_type}`) → Context: `{svc.bounded_context_name}`")
    return "\n".join(lines)


def _c4_container_doc(package: ArchitecturePackage) -> str:
    lines = [
        f"# C4 Container Diagram — {package.name}",
        "",
        "```mermaid",
        "flowchart TB",
        "  User([Enterprise Architect])",
        "",
    ]
    for svc in package.services:
        node_id = svc.name.replace(" ", "_").replace("-", "_")
        lines.append(f"  {node_id}[{svc.name}\\n{svc.service_type}]")
    lines.append("")
    for api in package.apis:
        src = api.service_name.replace(" ", "_").replace("-", "_")
        lines.append(f"  User -->|{api.method} {api.path}| {src}")
    lines.extend(["```", "", f"*Generated by ArchSmith v{package.version} — arc42 aligned*"])
    return "\n".join(lines)


def _openapi_doc(package: ArchitecturePackage) -> str:
    grouped: dict[str, list[API]] = defaultdict(list)
    for api in package.apis:
        grouped[api.path].append(api)

    lines = [
        "openapi: 3.1.0",
        f"info:",
        f"  title: {package.name} API",
        f"  version: {package.version}.0.0",
        f"  description: Auto-generated OpenAPI spec by ArchSmith",
        "paths:",
    ]
    for path, apis in grouped.items():
        lines.append(f"  {path}:")
        for item in apis:
            lines.append(f"    {item.method.lower()}:")
            lines.append(f"      operationId: {item.name.replace(' ', '')}")
            lines.append(f"      summary: {item.name}")
            lines.append(f"      tags: [{item.service_name}]")
            lines.append("      responses:")
            lines.append("        '200':")
            lines.append("          description: Success")
            lines.append("        '400':")
            lines.append("          description: Bad Request")
    return "\n".join(lines)


def _asyncapi_doc(package: ArchitecturePackage) -> str:
    lines = [
        "asyncapi: 2.6.0",
        "info:",
        f"  title: {package.name} Event Streams",
        f"  version: {package.version}.0.0",
        f"  description: Auto-generated AsyncAPI spec by ArchSmith",
        "channels:",
    ]
    for event in package.events:
        channel = event.name.replace(" ", ".").lower()
        lines.append(f"  {channel}:")
        lines.append("    publish:")
        lines.append(f"      summary: Produced by {event.producer_service or 'unknown'}")
        lines.append(f"      message:")
        lines.append(f"        name: {event.name}")
        lines.append(f"        payload:")
        lines.append(f"          type: object")
    return "\n".join(lines)


def _terraform_doc(package: ArchitecturePackage) -> str:
    lines = [
        f"# Terraform Blueprint — {package.name}",
        f"# Auto-generated by ArchSmith (FR4: Multi-cloud blueprint generation)",
        "",
        'terraform {',
        '  required_version = ">= 1.6.0"',
        '  required_providers {',
        '    aws = { source = "hashicorp/aws", version = "~> 5.0" }',
        '  }',
        '}',
        "",
        'variable "environment" { default = "production" }',
        "",
    ]
    for component in package.infra_components:
        rname = component.name.replace("-", "_").replace(" ", "_").lower()
        lines.append(f'resource "null_resource" "{rname}" {{')
        lines.append("  triggers = {")
        lines.append(f'    cloud       = "{component.cloud}"')
        lines.append(f'    component   = "{component.name}"')
        lines.append(f'    environment = var.environment')
        lines.append("  }")
        lines.append("}")
        lines.append("")
    for node in package.deployment_nodes:
        nname = node.name.replace("-", "_").replace(" ", "_").lower()
        lines.append(f'# Deployment node: {node.name} ({node.platform})')
        lines.append(f'output "{nname}_platform" {{')
        lines.append(f'  value = "{node.platform}"')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _adr_doc(package: ArchitecturePackage) -> str:
    lines = [f"# Architecture Decision Records — {package.name}", ""]
    for adr in package.adrs:
        lines.extend([
            f"---",
            f"## {adr.title}",
            f"**Status:** {adr.status}",
            f"",
            f"**Context:** {adr.context}",
            f"",
            f"**Decision:** {adr.decision}",
            f"",
        ])
    if not package.adrs:
        lines.append("*No ADRs recorded yet. Approve the package to generate a governance ADR.*")
    return "\n".join(lines)


def _impact_baseline_doc(package: ArchitecturePackage) -> str:
    lines = [f"# Impact Analysis Baseline — {package.name}", ""]
    lines.append("## Service Inventory")
    for svc in package.services:
        lines.append(f"- `{svc.name}` ({svc.service_type}) — context: {svc.bounded_context_name}")
    lines.append("\n## API Surface")
    for api in package.apis:
        lines.append(f"- `{api.method} {api.path}` — {api.name} (owned by {api.service_name})")
    lines.append("\n## Domain Events")
    for event in package.events:
        lines.append(f"- `{event.name}` — producer: {event.producer_service or 'unknown'}")
    lines.append("\n## Data Entities")
    for entity in package.data_entities:
        lines.append(f"- `{entity.name}` — owner: {entity.owning_service or 'unknown'}")
    return "\n".join(lines)


def _arc42_doc(package: ArchitecturePackage) -> str:
    fr_reqs = [r for r in package.requirements if r.category.upper() == "FR"]
    nfr_reqs = [r for r in package.requirements if r.category.upper() == "NFR"]
    fr_lines = [f"- **{r.key}** ({r.priority}): {r.text}" for r in fr_reqs] or ["- (none specified)"]
    nfr_lines = [f"- **{r.key}** ({r.priority}): {r.text}" for r in nfr_reqs] or ["- (none specified)"]
    svc_lines = [f"- {svc.name} ({svc.service_type})" for svc in package.services] or ["- (none defined)"]
    api_lines = [f"- {api.method} {api.path} → {api.name}" for api in package.apis] or ["- (no APIs defined)"]
    node_lines = [f"- {node.name} ({node.platform})" for node in package.deployment_nodes] or ["- kubernetes (default)"]
    return "\n".join([
        f"# arc42 Architecture Documentation — {package.name}",
        f"*Version {package.version} · Generated by ArchSmith*",
        "",
        "## 1. Introduction and Goals",
        package.description or f"Architecture package for {package.name}.",
        "",
        "## 2. Functional Requirements",
        *fr_lines,
        "",
        "## 3. Non-Functional Requirements",
        *nfr_lines,
        "",
        "## 4. Architecture Constraints",
        "- Multi-cloud blueprint support (FR4)",
        "- Governance and approval workflow (FR6)",
        "- RBAC and tenant isolation",
        "- Traceability from requirements to ADRs (FR2)",
        "",
        "## 5. Context and Scope",
        f"The {package.name} system comprises {len(package.services)} services across {len(package.domains)} domains.",
        "",
        "## 6. Solution Strategy",
        "- Domain-driven bounded contexts",
        "- API-first and event-first contracts",
        "- Automated impact analysis before changes (FR3)",
        "- Standards-aligned artifact generation (FR5)",
        "",
        "## 7. Building Blocks",
        *svc_lines,
        "",
        "## 8. Runtime View",
        *api_lines,
        "",
        "## 9. Deployment View",
        *node_lines,
        "",
        "## 10. Quality Scenarios",
        "- 99.9% uptime — all critical paths load-balanced",
        "- < 30s artifact generation per FR5",
        "- Zero breaking changes without impact analysis gate",
    ])


def generate_adr_candidates(package: ArchitecturePackage) -> list[ADR]:
    adrs: list[ADR] = []
    if package.services:
        adrs.append(ADR(
            package_id=package.id,
            title="ADR-001 Adopt Service-Oriented Bounded Contexts",
            status="proposed",
            context="Multiple bounded contexts require independent deployment and scaling.",
            decision="Align service boundaries to DDD bounded contexts for independent lifecycle management.",
        ))
    if package.events:
        adrs.append(ADR(
            package_id=package.id,
            title="ADR-002 Event-Driven Integration Pattern",
            status="proposed",
            context="Cross-service communication requires loose coupling to support resilience.",
            decision="Use async domain events for cross-context workflows; reserve REST for synchronous reads.",
        ))
    if package.infra_components:
        adrs.append(ADR(
            package_id=package.id,
            title="ADR-003 Multi-Cloud Infrastructure Strategy",
            status="proposed",
            context="Infrastructure components span multiple cloud providers.",
            decision="Use Terraform modules abstracted per cloud provider; enable portability via null_resource wrappers.",
        ))
    return adrs


def generate_artifacts(db: Session, package: ArchitecturePackage) -> list[Artifact]:
    if not package.adrs:
        for adr in generate_adr_candidates(package):
            db.add(adr)
        db.flush()
        db.refresh(package)

    reqs = list(package.requirements)
    adrs = list(package.adrs)
    trace = _traceability(reqs, adrs)

    definitions = [
        ("domain_model",    "Domain Model Documentation",          _domain_doc(package)),
        ("c4",              "C4 Container Diagram",                 _c4_container_doc(package)),
        ("openapi",         "OpenAPI Specification",                _openapi_doc(package)),
        ("asyncapi",        "AsyncAPI Event Specification",         _asyncapi_doc(package)),
        ("terraform",       "Infrastructure Blueprint (Terraform)",  _terraform_doc(package)),
        ("adr",             "Architecture Decision Records",         _adr_doc(package)),
        ("impact_baseline", "Impact Analysis Baseline",             _impact_baseline_doc(package)),
        ("arc42",           "arc42 Full Architecture Pack",          _arc42_doc(package)),
    ]

    artifacts: list[Artifact] = []
    for artifact_type, name, content in definitions:
        artifacts.append(Artifact(
            package_id=package.id,
            artifact_type=artifact_type,
            name=name,
            version=package.version,
            content=content,
            traceability=trace,
        ))
    return artifacts
